envc work

diff --git a/envc b/envc
--- a/envc
+++ b/envc
@@ -8,7 +8,12 @@ function main() {
 
     local command=$1
 
-    [ -z "${command}" ] && { echo "[error]: a command must be specified" 1>&2; exit 1; }
+    [ -z "${command}" ] && {
+
+        echo "[error]: a command must be specified" 1>&2;
+        echo "available commands:" 1>&2;
+        exit 1;
+    }
 
     if [ "${command}" = "start" ]; then
         start;
