added remove-snapshot

diff --git a/envc b/envc
--- a/envc
+++ b/envc
@@ -11,13 +11,17 @@ function main() {
     [ -z "${command}" ] && {
 
         echo "[error]: a command must be specified" 1>&2;
+        echo "" 1>&2;
         echo "available commands:" 1>&2;
+        echo "" 1>&2;
         echo " start [vmid]" 1>&2;
         echo " stop [vmid]" 1>&2;
         echo " status [vmid]" 1>&2;
         echo " snapshot <snapshot_tag> [vmid]" 1>&2;
         echo " list-snapshots [vmid]" 1>&2;
         echo " restore <snapshot_tag> [vmid]" 1>&2;
+        echo " remove-snapshot <snapshot_tag> [vmid]" 1>&2;
+        echo "" 1>&2;
         exit 1;
     }
 
@@ -33,6 +37,8 @@ function main() {
         list-snapshots $2;
     elif [ "${command}" = "restore" ]; then
         restore $2 $3;
+    elif [ "${command}" = "remove-snapshot" ]; then
+        remove-snapshot $2 $3;
     else
         echo "[error]: unknown command '${command}'" 1>&2;
         exit 1;
@@ -185,6 +191,47 @@ function restore() {
     for i in ${names}; do
         local image_volume=/main-storage-pool/${i}.qcow2
         qemu-img snapshot -a ${snapshot_tag} ${image_volume} && echo "${image_volume} restored to snapshot '${snapshot_tag}'" || exit 1
+    done
+}
+
+#
+# Removes the specified snapshot from all or just the specified virtual machine's qcow2 images.
+#
+# arg1 (required) the tag of the snapshot to be removed.
+# arg2 (optional) the vmid. If not specified, the snapshot will be removed from all virtual machines.
+#
+function remove-snapshot() {
+
+    local snapshot_tag=$1
+
+    [ -z "${snapshot_tag}" ] && { echo "[error]: a snapshot tag must be specified" 1>&2; exit 1; }
+
+    local names
+    names=$(filter $2) || exit 1
+
+    # make sure the target guests are down. If at least one is up, fail
+
+    for i in ${names}; do
+        local state
+        state=$(virsh domstate ${i}) || exit 1
+        if [ "${state}" != "shut off" ]; then
+           echo "'${i}' is not shut down, cannot remove snapshot ..." 1>&2
+           exit 1
+        fi
+    done
+
+    # list the qcow2 images
+
+    for i in ${names}; do
+        local image_volume=/main-storage-pool/${i}.qcow2
+        virsh vol-info ${image_volume} || { echo "failed to query ${image_volume}" 1>&2; exit 1; }
+    done
+
+    # remove
+
+    for i in ${names}; do
+        local image_volume=/main-storage-pool/${i}.qcow2
+        qemu-img snapshot -d ${snapshot_tag} ${image_volume} && echo "'${snapshot_tag}' snapshot removed from ${image_volume}" || exit 1
     done
 }
 
