export-guest (3)

diff --git a/export-guest b/export-guest
--- a/export-guest
+++ b/export-guest
@@ -80,7 +80,14 @@ function main() {
 
   virsh undefine ${guest_name} || { echo "failed to remove guest ${guest_name}" 1>&2; exit 1; }
 
-  echo "all done"
+  echo "packaging guest ${guest_name} artifacts ..."
+
+  (cd ${export_root}; tar cfv - ${guest_name} | gzip > ${guest_name}.tar.gz) || { echo "failed to package guest ${guest_name} artifacts" 1>&2; exit 1; }
+
+  rm -r ${export_root}/${guest_name} || { echo "failed to rm ${export_root}/${guest_name}" 1>&2; exit 1; }
+
+  echo "${guest_name}.tar.gz ready for upload"
+
 }
 
 main $@
